version: "3.9"

services:
  de_mysql:
    image: mysql:8.0
    container_name: de_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
    networks:
      - de_network

  de_psql:
    image: postgres:15
    container_name: de_psql
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - de_network

  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    env_file:
      - .env
    networks:
      - de_network

  mc:
    image: minio/mc
    hostname: mc
    container_name: mc
    entrypoint: >
      /bin/sh -c "until (/usr/bin/mc config host add minio http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY) do echo '...waiting...'; sleep 1; done; /usr/bin/mc mb minio/warehouse; /usr/bin/mc policy set public minio/warehouse; exit 0;"
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
